#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__
enum {	
	TRANS_CLIENT_CONNECTED,	
	TRANS_CLIENT_DISCONNECTED,	
	TRANS_RECV_DATA_FROM_UART,	
	TRANS_SEND_DATA_TO_UART_OVER,
	};

#define TRANS_TASK_PROI	0

#endif

